
  SELECT  'TARTI' , IDART,  0,   LIBART,  QTEART
    FROM  ADCDE.TARTI
    UNION
  SELECT  'TDECL' , IDART, IDDEC , COLORIS , QTES
    FROM  ADCDE.TDECL
    UNION
  SELECT  'SEUL ' , IDART,  0, '-----' ,  QTEART
    FROM  ADCDE.TARTI
    WHERE IDART NOT IN
     ( SELECT D.IDART
         FROM  TDECL D
     )
    UNION
  SELECT  'SOMME' ,  A.IDART , 0 , LIBART  , SUM(QTES)
    FROM  ADCDE.TDECL D , ADCDE.TARTI  A
    WHERE  D.IDART  = A.IDART
    GROUP BY A.IDART, LIBART
    ORDER BY 2,  1 , 3
         ;
